### PR TITLE
Add dotenv

### PR DESCRIPTION
**Pull request by twilwa**
Should resolve issue #24 . I beleive I caught everything, but haven't written a test suite to verify, take a look and see if it looks good. Since the json configs are necessary (as far as I know), modified the inits to inject the env vars at runtime.

### CODE REVIEW

**Comment by twilwa** [comment]
rip i forgot to point this at dev instead of main, bad boy

**Comment by Josephrp** [comment]
auto-pr is not retained here , please verify the above accordingly

**Comment by Josephrp** [comment]
the files list can be used for the readme

**Comment by Josephrp** [comment]
the changes above are not correctly documented and modify the way the configurations are loaded without modifying the configuration method in each module.

**Pull request closed without merging**
